name: Build and Deploy

on:
  push:
    branches: [ "slave" ]
  pull_request:
    branches: [ "slave" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Build and then Deploy the static react canary app that uses the react adobe coponent
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
    
    